name: Deploy Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Container Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        # Replace with your container registry credentials stored as secrets

      - name: Pull Docker Image
        run: docker pull ayodev581/simple-web-app:latest
        # Replace with your Docker image details (name and tag)

      - name: Run Docker Container
        run: |
          docker run -d -p 80:80 simple-web-app:latest
          # Replace with your Docker image details (name and tag)
        env:
          MY_ENV_VAR: some_value
          # Set any environment variables your app requires

      - name: Check Deployment
        run: curl -Is http://localhost | head -n 1
        # Use a curl command or other tool to check that your app is running

      - name: Deploy Completed
        run: echo "Deployment completed."
